### ISSUE TITLE
NPC Chatter Is Only Seen By One PC

### ISSUE THREAD

**Issue by DM-ex-Machina** [cswendrowski/FoundryVtt-Npc-Chatter#2]
So, after testing NPC Chatter in use with Trigger Happy, I suddenly hit a strange issue. Evidently the only person who sees the chat bubble is whoever is in control of the token that runs over it. If my player walks their token over the Trigger, I don't see any chat bubble. And if I take control of my player's token and walk it over the Trigger for them, they don't see the chat bubble. 

Also, possibly unrelated, but every attempt I've made to recreate a Trigger with an NPC Chatter set up hasn't worked. The original Trigger and NPC Chatter that I made my initial test with is still working (other than the above stated issue), but any subsequent attempt to recreate that hasn't worked.

**Comment by gblosser42** [comment]
I fixed the issue locally, and am willing to share the code if you want it.

Basically, the issue is that creating a chat bubble is done client-side. Since the bubble is created directly from the macro script execution, it only happens on whoever is running the script.

I got around this by having the script create an ambient light source whose tintColor is the data needed to generate the bubble. Then, I added a hook to the creation of an invisible ambient light source so everyone connecting will react to it. They parse the tintColor and create the appropriate chat bubble. Then the light source is deleted.


Code is here if you want it: https://pastebin.com/S236EXz1
Couldn't submit a pull request due to permissions settings of the repo

**Comment by cswendrowski** [comment]
@gblosser42 That's an interesting way to solve the problem! I'll verify it tomorrow, and pull it in if so.

In Github, the way to issue a PR is to first Fork the repo, make your changes there, and then issue a PR from your repo to the original one

**Comment by cswendrowski** [comment]
@gblosser42 apologies for the long delay, but this is resolved as of v2.0.0
